### ISSUE TITLE
[Suggestion] Registering LootTables so that LootTweaker can access them?

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/ERZ#13]
Hi again,

Would it be possible to have this mod's mobs loottables be accessible by LootTweaker? Right now doing /mt loottables all doesn't dump the Loot Tables for the mobs or doesn't detect it. I know you said in the CurseForge description that it uses the vanilla JSON system, but I've always found that using Zenscript and LootTweaker to alter those JSON's to be much easier for me and kept things neater. 

Thanks again,

**Comment by Lothrazar** [comment]
Yeah i use loot table .json files, so i dont know why loot tweaker cant see them.
https://github.com/PrinceOfAmber/ERZ/tree/master/src/main/resources/assets/emberroot/loot_tables/entity

Which project are you using, seems like two versions for some reason? 
https://www.curseforge.com/minecraft/mc-mods/loottweaker

or
https://www.curseforge.com/minecraft/mc-mods/loottabletweaker

**Comment by Vyraal1** [comment]
I am using the first one, LootTweaker. Also maybe @Leviathan143 could provide more insight for whi the files aren't being detected.

I'm verifying this by starting up the game and doing /ct loottables all which dumps all of the available loottables into the modpack folder under the "dumps" folder.

**Comment by Daomephsta** [comment]
@PrinceOfAmber 
LootTweaker uses the global list of all built in loot tables in `LootTableList` to check if a loot table exists. All you need to do is register your loot tables by calling `LootTableList.register()` with the loot table's resource location as the argument.

Note: If you register the loot tables in the initializer of a static field, as vanilla does, please add a dummy method that you call in preinit to force the JVM to initialize the class. Otherwise they won't be registered when mods like LootTweaker check to make sure a table with a particular name exists.

Oh, and there aren't two different versions. LootTweaker & LootTableTweaker are similar projects with similar names, but they are by different authors (I dev the former, DarkHax devs the latter).

**Comment by Vyraal1** [comment]
Hey @PrinceOfAmber, just wanted to follow up on this, any luck on getting the loot tables exposed for LootTweaker? I stopped work on Interaction and working on the ATM team for their next expert pack, and wanted to alter some drop rates. Thanks!

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/emberroot-zoo/files/2599195
